const FRUIT_EMOJI_MAP: Record<string, string> = {
  'Grão de areia':       '🌱',
  'Semente de papoula':  '🌸',
  'Semente de gergelim': '🌾',
  'Lentilha':            '🫘',
  'Mirtilo':             '🫐',
  'Framboesa':           '🍓',
  'Uva':                 '🍇',
  'Morango':             '🍓',
  'Limão':               '🍋',
  'Ameixa':              '🍑',
  'Pêssego':             '🍑',
  'Limão siciliano':     '🍋',
  'Maçã':                '🍎',
  'Abacate':             '🥑',
  'Pera':                '🍐',
  'Batata-doce':         '🍠',
  'Manga':               '🥭',
  'Banana':              '🍌',
  'Cenoura':             '🥕',
  'Mamão papaia':        '🍈',
  'Toranja':             '🍊',
  'Espiga de milho':     '🌽',
  'Couve-flor':          '🥦',
  'Alface':              '🥬',
  'Couve-flor grande':   '🥦',
  'Berinjela':           '🍆',
  'Abóbora':             '🎃',
  'Repolho':             '🥬',
  'Coco':                '🥥',
  'Jicama':              '🥔',
  'Abacaxi':             '🍍',
  'Melão cantaloupe':    '🍈',
  'Melão honeydew':      '🍈',
  'Alface americana':    '🥬',
  'Acelga':              '🥬',
  'Alho-poró':           '🧅',
  'Mini melancia':       '🍉',
  'Melancia':            '🍉',
};

export function getFruitEmoji(comparison: string): string {
  if (comparison === '—' || comparison === '') return '👶';
  return FRUIT_EMOJI_MAP[comparison] ?? '🌿';
}
